-- Public drill library, part 3: taxonomy seeding for the 6-sport public
-- library import (ROP-Public-Library-Spec.md §0.2/§1.3/§1.4).
--
-- Categories: Football/Lacrosse/Soccer/Volleyball had zero skill_categories
-- before this (see 20260707090000_seed_skill_categories.sql -- only
-- Baseball/Basketball existed). Order/names match the spec's proposed
-- taxonomy verbatim, and match what the drill JSON files already use.
insert into public.skill_categories (sport, name, sort_order) values
  ('Football', 'Passing', 1),
  ('Football', 'Receiving', 2),
  ('Football', 'Rushing', 3),
  ('Football', 'Blocking', 4),
  ('Football', 'Tackling', 5),
  ('Football', 'Conditioning', 6),
  ('Football', 'Team Play', 7),
  ('Soccer', 'Passing', 1),
  ('Soccer', 'Shooting', 2),
  ('Soccer', 'Dribbling', 3),
  ('Soccer', 'Defending', 4),
  ('Soccer', 'Goalkeeping', 5),
  ('Soccer', 'Conditioning', 6),
  ('Soccer', 'Team Play', 7),
  ('Lacrosse', 'Passing', 1),
  ('Lacrosse', 'Shooting', 2),
  ('Lacrosse', 'Dodging', 3),
  ('Lacrosse', 'Defending', 4),
  ('Lacrosse', 'Ground Balls', 5),
  ('Lacrosse', 'Conditioning', 6),
  ('Lacrosse', 'Team Play', 7),
  ('Volleyball', 'Serving', 1),
  ('Volleyball', 'Passing', 2),
  ('Volleyball', 'Setting', 3),
  ('Volleyball', 'Hitting', 4),
  ('Volleyball', 'Blocking', 5),
  ('Volleyball', 'Conditioning', 6),
  ('Volleyball', 'Team Play', 7);

-- Global tags for all 6 sports. Football/Soccer/Lacrosse/Volleyball get
-- their full newTagProposals list from each sport's JSON file (the sport's
-- complete proposed taxonomy, not just the subset a seed drill happens to
-- use today -- same role the pre-existing Baseball/Basketball lists play).
-- Baseball/Basketball get TRUE global rows for their existing taxonomy --
-- until now only scope='coach' per-coach copies existed (seeded by
-- 20260711000000_seed_default_skill_tags.sql, whose own comment flags this
-- gap: "I still need to create real global-scope rows with these names").
-- NOT EXISTS guard makes this safe to re-run.
insert into public.skill_tags (category_id, scope, name)
select sc.id, 'global', v.tag_name
from (values
  ('Football', 'Passing', 'Throwing mechanics'),
  ('Football', 'Passing', 'Footwork & drops'),
  ('Football', 'Passing', 'Throwing on the move'),
  ('Football', 'Passing', 'Reading coverage'),
  ('Football', 'Receiving', 'Catching fundamentals'),
  ('Football', 'Receiving', 'Route running'),
  ('Football', 'Receiving', 'Contested catches'),
  ('Football', 'Receiving', 'Releases & separation'),
  ('Football', 'Rushing', 'Ball security'),
  ('Football', 'Rushing', 'Vision & cuts'),
  ('Football', 'Rushing', 'Handoff exchange'),
  ('Football', 'Rushing', 'Open-field running'),
  ('Football', 'Blocking', 'Stance & first step'),
  ('Football', 'Blocking', 'Hand placement'),
  ('Football', 'Blocking', 'Drive blocking'),
  ('Football', 'Blocking', 'Pass protection'),
  ('Football', 'Tackling', 'Form tackling'),
  ('Football', 'Tackling', 'Pursuit angles'),
  ('Football', 'Tackling', 'Wrap & drive'),
  ('Football', 'Tackling', 'Open-field tackling'),
  ('Football', 'Conditioning', 'Speed & acceleration'),
  ('Football', 'Conditioning', 'Agility & change of direction'),
  ('Football', 'Conditioning', 'Explosiveness'),
  ('Football', 'Conditioning', 'Endurance'),
  ('Football', 'Team Play', 'Play execution'),
  ('Football', 'Team Play', 'Situational football'),
  ('Football', 'Team Play', 'Communication'),
  ('Football', 'Team Play', 'Special teams basics'),

  ('Lacrosse', 'Passing', 'Stationary passing & catching'),
  ('Lacrosse', 'Passing', 'Passing on the run'),
  ('Lacrosse', 'Passing', 'Quick stick'),
  ('Lacrosse', 'Passing', 'Off-hand development'),
  ('Lacrosse', 'Shooting', 'Shooting on the run'),
  ('Lacrosse', 'Shooting', 'Time & room shooting'),
  ('Lacrosse', 'Shooting', 'Shot placement'),
  ('Lacrosse', 'Shooting', 'Crease finishing'),
  ('Lacrosse', 'Dodging', 'Split dodge'),
  ('Lacrosse', 'Dodging', 'Roll dodge'),
  ('Lacrosse', 'Dodging', 'Dodging from X'),
  ('Lacrosse', 'Dodging', 'Change of pace'),
  ('Lacrosse', 'Defending', 'Approach & breakdown footwork'),
  ('Lacrosse', 'Defending', 'Stick checks'),
  ('Lacrosse', 'Defending', 'Body positioning'),
  ('Lacrosse', 'Defending', 'Slides & recovery'),
  ('Lacrosse', 'Ground Balls', 'Scooping technique'),
  ('Lacrosse', 'Ground Balls', 'Contested ground balls'),
  ('Lacrosse', 'Ground Balls', 'Ground ball to fast break'),
  ('Lacrosse', 'Ground Balls', 'Boxing out'),
  ('Lacrosse', 'Conditioning', 'Speed & agility'),
  ('Lacrosse', 'Conditioning', 'Acceleration'),
  ('Lacrosse', 'Conditioning', 'Endurance'),
  ('Lacrosse', 'Conditioning', 'Transition running'),
  ('Lacrosse', 'Team Play', 'Fast break offense'),
  ('Lacrosse', 'Team Play', 'Clearing'),
  ('Lacrosse', 'Team Play', 'Off-ball movement'),
  ('Lacrosse', 'Team Play', 'Man-up / man-down basics'),

  ('Soccer', 'Passing', 'Short passing accuracy'),
  ('Soccer', 'Passing', 'Receiving / first touch'),
  ('Soccer', 'Passing', 'Long balls & switching play'),
  ('Soccer', 'Passing', 'Passing under pressure'),
  ('Soccer', 'Shooting', 'Finishing technique'),
  ('Soccer', 'Shooting', 'Shooting off the dribble'),
  ('Soccer', 'Shooting', 'Volleys & first-time finishes'),
  ('Soccer', 'Shooting', '1v1 vs goalkeeper'),
  ('Soccer', 'Dribbling', 'Close control'),
  ('Soccer', 'Dribbling', 'Change of direction / moves'),
  ('Soccer', 'Dribbling', 'Speed dribbling'),
  ('Soccer', 'Dribbling', 'Shielding the ball'),
  ('Soccer', 'Defending', '1v1 defending'),
  ('Soccer', 'Defending', 'Pressing & angles'),
  ('Soccer', 'Defending', 'Tackling technique'),
  ('Soccer', 'Defending', 'Defensive shape'),
  ('Soccer', 'Goalkeeping', 'Handling & catching'),
  ('Soccer', 'Goalkeeping', 'Footwork & positioning'),
  ('Soccer', 'Goalkeeping', 'Shot stopping'),
  ('Soccer', 'Goalkeeping', 'Distribution'),
  ('Soccer', 'Conditioning', 'Speed & agility'),
  ('Soccer', 'Conditioning', 'Acceleration'),
  ('Soccer', 'Conditioning', 'Endurance'),
  ('Soccer', 'Conditioning', 'Small-sided fitness'),
  ('Soccer', 'Team Play', 'Possession play'),
  ('Soccer', 'Team Play', 'Small-sided games'),
  ('Soccer', 'Team Play', 'Transition play'),
  ('Soccer', 'Team Play', 'Combination play'),

  ('Volleyball', 'Serving', 'Serve mechanics'),
  ('Volleyball', 'Serving', 'Serve placement'),
  ('Volleyball', 'Serving', 'Serving under pressure'),
  ('Volleyball', 'Serving', 'Short & deep variation'),
  ('Volleyball', 'Passing', 'Forearm platform'),
  ('Volleyball', 'Passing', 'Serve receive'),
  ('Volleyball', 'Passing', 'Passing footwork'),
  ('Volleyball', 'Passing', 'Free-ball passing'),
  ('Volleyball', 'Setting', 'Hand shape & contact'),
  ('Volleyball', 'Setting', 'Setter footwork'),
  ('Volleyball', 'Setting', 'Out-of-system setting'),
  ('Volleyball', 'Setting', 'Setter decision-making'),
  ('Volleyball', 'Hitting', 'Approach footwork'),
  ('Volleyball', 'Hitting', 'Arm swing mechanics'),
  ('Volleyball', 'Hitting', 'Hitting off a live set'),
  ('Volleyball', 'Hitting', 'Tips & shot placement'),
  ('Volleyball', 'Blocking', 'Block footwork'),
  ('Volleyball', 'Blocking', 'Hand position & penetration'),
  ('Volleyball', 'Blocking', 'Reading the hitter'),
  ('Volleyball', 'Blocking', 'Transition off the block'),
  ('Volleyball', 'Conditioning', 'Speed & agility'),
  ('Volleyball', 'Conditioning', 'Jumping & explosiveness'),
  ('Volleyball', 'Conditioning', 'Court movement endurance'),
  ('Volleyball', 'Conditioning', 'Quick reactions'),
  ('Volleyball', 'Team Play', 'Serve receive rotations'),
  ('Volleyball', 'Team Play', 'Defense & coverage'),
  ('Volleyball', 'Team Play', 'Transition offense'),
  ('Volleyball', 'Team Play', 'Communication'),

  ('Baseball', 'Hitting', 'Bat path'),
  ('Baseball', 'Hitting', 'Timing / pitch recognition'),
  ('Baseball', 'Hitting', 'Contact to all fields'),
  ('Baseball', 'Hitting', 'Two-strike approach'),
  ('Baseball', 'Fielding', 'Glove work / fundamentals'),
  ('Baseball', 'Fielding', 'First-step reads'),
  ('Baseball', 'Fielding', 'Footwork on ground balls'),
  ('Baseball', 'Fielding', 'Pop-up communication'),
  ('Baseball', 'Pitching', 'Mechanics / delivery'),
  ('Baseball', 'Pitching', 'Command'),
  ('Baseball', 'Pitching', 'Pitch mix'),
  ('Baseball', 'Pitching', 'Pickoff moves'),
  ('Baseball', 'Throwing', 'Arm action'),
  ('Baseball', 'Throwing', 'Accuracy'),
  ('Baseball', 'Throwing', 'Crow hops / transfers'),
  ('Baseball', 'Throwing', 'Long toss'),
  ('Baseball', 'Baserunning', 'Leads and reads'),
  ('Baseball', 'Baserunning', 'First-to-third'),
  ('Baseball', 'Baserunning', 'Sliding technique'),
  ('Baseball', 'Baserunning', 'Stealing bags'),
  ('Baseball', 'Conditioning', 'Speed / sprint work'),
  ('Baseball', 'Conditioning', 'Agility'),
  ('Baseball', 'Conditioning', 'Strength'),
  ('Baseball', 'Conditioning', 'Endurance'),
  ('Baseball', 'Team Play', 'Cutoffs and relays'),
  ('Baseball', 'Team Play', 'Situational awareness'),
  ('Baseball', 'Team Play', 'Communication'),
  ('Baseball', 'Team Play', 'Bunt defense'),

  ('Basketball', 'Shooting', 'Form / mechanics'),
  ('Basketball', 'Shooting', 'Catch-and-shoot'),
  ('Basketball', 'Shooting', 'Off the dribble'),
  ('Basketball', 'Shooting', 'Free throws'),
  ('Basketball', 'Ball Handling', 'Dribble control'),
  ('Basketball', 'Ball Handling', 'Change of direction'),
  ('Basketball', 'Ball Handling', 'Weak-hand development'),
  ('Basketball', 'Ball Handling', 'Pressure handling'),
  ('Basketball', 'Passing', 'Chest / bounce pass'),
  ('Basketball', 'Passing', 'Court vision'),
  ('Basketball', 'Passing', 'Passing off the dribble'),
  ('Basketball', 'Passing', 'Entry passes'),
  ('Basketball', 'Defense', 'On-ball defense'),
  ('Basketball', 'Defense', 'Help defense'),
  ('Basketball', 'Defense', 'Closeouts'),
  ('Basketball', 'Defense', 'Screen navigation'),
  ('Basketball', 'Rebounding', 'Boxing out'),
  ('Basketball', 'Rebounding', 'Positioning'),
  ('Basketball', 'Rebounding', 'Put-backs'),
  ('Basketball', 'Rebounding', 'Long rebounds'),
  ('Basketball', 'Conditioning', 'Speed / sprint work'),
  ('Basketball', 'Conditioning', 'Agility'),
  ('Basketball', 'Conditioning', 'Strength'),
  ('Basketball', 'Conditioning', 'Endurance'),
  ('Basketball', 'Team Play', 'Spacing'),
  ('Basketball', 'Team Play', 'Ball movement'),
  ('Basketball', 'Team Play', 'Transition offense'),
  ('Basketball', 'Team Play', 'Communication')
) as v(sport, category, tag_name)
join public.skill_categories sc on sc.sport = v.sport and sc.name = v.category
where not exists (
  select 1 from public.skill_tags st
  where st.category_id = sc.id and st.scope = 'global' and st.name = v.tag_name
);
